env: prd


spring:
  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: 192.168.160.131 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password:   # Redis服务器连接密码（默认为空）
    timeout: 1000    # 连接超时时间（毫秒）
    pool:
      max-active: 200  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10    # 连接池中的最大空闲连接
      min-idle: 0   # 连接池中的最小空闲连接

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.160.131:3306/test #?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456